import json
from lib import I
O='/mnt/user-data/outputs/kataki-design/design-system'
T=json.load(open(f'{O}/tokens.json'))
sprite=open(f'{O}/icons/sprite.svg').read()
C='../assets/characters/'; P='../assets/places/'
def ic(n,cls='k-icon'): return f'<svg class="{cls}" aria-hidden="true"><use href="#i-{n}"/></svg>'
def av(who,img=None,s=44,cls='',extra=''):
    img=img or {'mira':'mira-neutral','tobin':'tobin-grin','ilsa':'ilsa-smile','oren':'oren-neutral','wren':'wren-smile','aren':'aren-neutral','sable':'sable-wary'}[who]
    return f'<span class="k-avatar {cls}" style="--s:{s}px; --bg: var(--k-char-{who}); {extra}"><img src="{C}{img}.svg" alt=""></span>'
def sw(name,val,dark=False):
    return f'<div class="sw"><span class="chip" style="background:{val}"></span><b>{name}</b><code>{val}</code></div>'
def section(id,title,desc,body,world='sky'):
    return f'<section id="{id}" class="sec sec--{world}"><header><h2>{title}</h2><p>{desc}</p></header>{body}</section>'
def demo(label, html, note=''):
    return f'<div class="demo"><div class="demo__stage">{html}</div><div class="demo__meta"><b>{label}</b>{("<p>"+note+"</p>") if note else ""}</div></div>'

# foundations
sky_sw=''.join(sw(k,v['value']) for k,v in T['sky'].items() if not v['value'].startswith('linear') and 'px' not in v['value'] and not v['value'].startswith('0 '))
scene_sw=''.join(sw(k,v['value']) for k,v in T['scene'].items() if isinstance(v,dict) and 'value' in v and v['value'].startswith(('#','rgba')))
bs_sw=''.join(sw(k,v['value']) for k,v in T['backstage'].items() if 'value' in v and v['value'].startswith(('#','rgba')))
candy=''.join(f'<div class="sw"><span class="k-candy k-candy--{k}">{ic(n)}</span><b>{k}</b><code>{a} → {b}</code></div>' for (k,(a,b)),n in zip(T['candy'].items(),['grid','heart','book','spark','users','star']))
chars=''.join(f'<div class="sw"><span class="chip" style="background:{v}"></span><b>{k}</b></div>' for k,v in T['character-bg'].items())
types=''.join(f'<div class="type"><span style="font-family: var(--k-font-{v["font"]}); font-size:{min(v["size"],64)}px; line-height:{v.get("line",1.3)}; font-weight:{v.get("weight",400)}; {"font-style:italic;" if v.get("style") else ""}{"letter-spacing:"+v["tracking"]+";" if v.get("tracking") else ""}{"text-transform:uppercase;" if v.get("transform") else ""}">{ {"story-body":"Coin first. Questions after.","hero":"They’ll remember this.","title-xl":"Six years later"}.get(k,"The Third Floorboard") }</span><code>{k} · {v["font"]} {v["size"]}px{(" / "+str(v["weight"])) if v.get("weight") else ""}</code></div>' for k,v in T['type'].items())
icons=''.join(f'<div class="ico">{ic(n)}<code>{n}</code></div>' for n in I)
found = section('foundations','Foundations','Tokens live in <code>tokens.json</code> and <code>tokens.css</code>. The Sky is bright glass over clouds; the Scene is warm lamplight over dark; Backstage is a blueprint.',
 f'<h3>Sky colours</h3><div class="grid">{sky_sw}</div><h3>Candy icon pairs</h3><div class="grid">{candy}</div><h3>Character backdrops</h3><div class="grid">{chars}</div>'
 f'<h3>Scene colours</h3><div class="grid dark">{scene_sw}</div><h3>Backstage colours</h3><div class="grid bp">{bs_sw}</div>'
 f'<h3>Type</h3><div class="types">{types}</div><h3>Icons ({len(I)})</h3><p class="hint">24×24, 1.8 stroke, round caps. Use <code>icons/sprite.svg</code> (<code>&lt;use href="#i-name"&gt;</code>) or <code>icons/icons.json</code>.</p><div class="icons">{icons}</div>')

CUR='aria-current="step"'
# sky components
fc=lambda who,img,name,tag,status,cls='': f'<a class="k-portrait k-friend-card" href="#" style="--bg: var(--k-char-{who});"><img src="{C}{img}.svg" alt="" style="top:6px; left:-22px; width:240px;"><span class="k-nameplate"><b style="font-size:16px">{name}</b><span style="font-size:11.5px;color:var(--k-sky-muted)">{tag}</span><span class="k-status {cls}" style="background:none;padding:0;height:auto;color:var(--k-sky-ink)">{status}</span></span></a>'
sky = section('sky','The Sky · components','Everything outside a story. Frosted glass, pill shapes, candy icons, playful bounce.',
 demo('Buttons', f'<div class="row"><button class="k-btn k-btn--dark">{ic("plus")}Add a friend</button><button class="k-btn k-btn--primary">Primary</button><button class="k-btn">{ic("users")}Start a group scene</button><button class="k-btn k-btn--ghost">Skip for now</button><button class="k-btn k-btn--danger k-btn--sm">Remove</button></div>','Dark is the main action on a screen; secondary is white glass. Min height 44 (34 for dense rows).')
 + demo('Orb', f'<div class="row"><button class="k-orb" aria-label="Dive back in"></button><button class="k-orb" style="--s:74px" aria-label="Dive back in"></button></div>','Always one click from anywhere in the Sky: rail bottom, Continue card, Message button. Dives into the last scene.')
 + demo('Chips, tags, status', f'<div class="row"><button class="k-chip" aria-pressed="true">All</button><button class="k-chip">One-to-one</button><button class="k-chip">{ic("spark")}Memories</button><span class="k-tag">Courier</span><span class="k-status">At The Gull · Year 7</span><span class="k-status k-status--idle">Not in a story yet</span><span class="k-status k-status--warn">key stored</span></div>')
 + demo('Candy filters', '<div class="row">'+''.join(f'<button class="k-candy-filter" aria-pressed="{"true" if i==0 else "false"}"><span class="k-candy k-candy--{c}">{ic(n)}</span>{l}</button>' for i,(l,n,c) in enumerate([('All','grid','blue'),('Favourites','heart','pink'),('In a story','book','purple'),('New','spark','green'),('Groups','users','orange')]))+'</div>')
 + demo('Avatars', f'<div class="row">{av("aren",s=62,cls="k-avatar--ring")}{av("mira")}{av("tobin",s=36)}{av("ilsa",s=24)}<span class="k-avatar-stack">{av("mira",s=40)}{av("tobin",s=40)}</span></div>','Circular crop of the portrait art; backdrop is the character colour.')
 + demo('Friend card', f'<div class="row">{fc("mira","mira-neutral","Mira","Guild courier. Loyal to friends, wary of everyone else.","● At The Gull · Year 7")}{fc("wren","wren-smile","Wren","Just added. Finish their profile.","○ Not in a story yet")}</div>','196×268. Name plate is strong glass over the portrait. Hover lifts.')
 + demo('Event item (Activity)', '<div style="width:420px;display:flex;flex-direction:column;gap:8px">'+''.join(f'<a class="k-event k-event--{k}" href="#"><span style="position:relative">{av(w)}<span class="k-event__kind">{ic(n,"k-icon")}</span></span><span><b style="font-size:14px">{t}</b><br><small style="color:var(--k-sky-muted)">The Third Floorboard · {c}</small></span></a>' for k,w,n,t,c in [('memory','mira','spark','Mira will remember that you hid the ledger.','Day 1'),('feeling','tobin','heart','Tobin didn’t like being sent to the bar.','Day 1'),('belief','mira','help','Mira has her doubts about the lighthouse.','Year 7'),('time','mira','clock','Six years passed. 12 memories went hazy.','Year 7')])+'</div>','Kind colours: memory gold, feeling pink, belief violet, time blue.')
 + demo('Cards', f'<div class="row" style="align-items:flex-start"><div class="k-card" style="width:300px"><h3>How she talks</h3><div style="display:flex;gap:8px;align-items:flex-end">{av("mira",s=30)}<span class="k-bubble">Coin first. Questions after.</span></div></div><div class="k-secret" style="width:300px"><b>{ic("lock")} Only Mira knows this</b><span class="k-secret__text">She reads every letter she carries.</span><button class="k-btn k-btn--sm" style="align-self:flex-start">{ic("eye")}Reveal as author</button></div><div class="k-card" style="width:260px;flex-direction:row;align-items:center"><span class="k-ring" style="--p:60">60%</span><span><b>Add a secret to make Wren more real</b></span></div></div>')
 + demo('Inputs', f'<div class="row" style="align-items:flex-start"><label class="k-search k-glass" style="width:320px">{ic("search")}<span class="k-sr">Search</span><input placeholder="Search friends, stories, places"></label><label class="k-field"><span>Model</span><select class="k-select"><option>qwen3.5-9b</option></select></label><div class="k-seg"><button aria-pressed="false">Balanced</button><button aria-pressed="true">Balanced + DRY</button><button aria-pressed="false">Focused</button></div></div><label class="k-field" style="margin-top:14px;width:520px"><span>Only Wren knows…</span><textarea class="k-textarea" rows="3" placeholder="Write it the way Wren would never say it out loud."></textarea></label>')
 + demo('Stepper', '<div style="width:260px">'+''.join(f'<button class="k-step {"is-done" if s=="d" else ""}" {CUR if s=="n" else ""}><span class="k-step__dot">{ic("check") if s=="d" else i+1}</span>{t}</button>' for i,(t,s) in enumerate([('Name and portrait','d'),('Who they are','d'),('Their secret','n'),('How they talk','t')]))+'</div>')
)

# scene components
rc=lambda who,st,s=16: (f'<span class="k-avatar k-receipt is-absent" style="--s:{s}px">{who[0].upper()}</span>' if st=='absent' else av(who,s=s,cls=f'k-receipt is-{st}'))
RE=lambda k,w,n,t: f'<span class="k-react k-react--{k}">{av(w,s=20)}{ic(n)}{t}</span>'
wchar = f"""<div class="k-widget" style="position:relative"><div class="k-widget__art"><img src="{C}mira-wary.svg" alt="Mira, uneasy"><button class="k-widget__pin" aria-label="Unpin Mira" aria-pressed="true">{ic("pushpin")}</button></div><div style="padding:10px 14px 13px;display:flex;flex-direction:column;gap:4px"><span style="display:flex;align-items:center;gap:8px"><b style="font-family:var(--k-font-story);font-size:20px;font-weight:400">Mira</b><span class="k-expr" style="--c:var(--k-scene-rose)">uneasy</span></span><small style="color:var(--k-scene-muted);font-size:12.5px">Worried someone overheard</small></div></div>"""
wrow = f"""<div class="k-widget k-widget--row is-away" style="position:relative">{av("tobin",s=40)}<span><b style="font-size:14px">Tobin</b><br><small style="color:var(--k-scene-muted)">At the bar · away</small></span></div>"""
wclock = f"""<div class="k-widget" style="position:relative;padding:14px 16px"><span class="k-clock__time" title="19:22 · Year 7, Day 1">7:22 pm</span><div style="font-size:13.5px;font-weight:600;margin-top:4px">Six years after the storm</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:10px"><small style="color:var(--k-scene-muted)">The Gull</small><button class="k-sbtn">{ic("clock")}Pass time</button></div></div>"""
wmusic = f"""<div class="k-widget" style="position:relative;display:flex;align-items:center;gap:12px;padding:12px 14px"><button class="k-sbtn" style="width:40px;height:40px;padding:0;justify-content:center;border-radius:50%" aria-label="Pause">{ic("stop")}</button><span style="flex-grow:1"><b style="font-size:13.5px">Night rain, empty harbour</b><br><small style="color:var(--k-scene-muted)">Matched to the scene</small></span><button class="k-sbtn" style="border:0" aria-label="Mute">{ic("volume")}</button></div>"""
scene = section('scene','The Scene · components','Inside a story. The chat runs the full height; everything else is a widget the user can move, pin, remove or add. Feelings show in the chat; hearing and engine detail stay in Advanced and Backstage.',
 demo('Line and reactions', f"""<div style="width:680px">
<article class="k-line" style="--speaker: var(--k-speaker-aren)"><div class="k-line__head"><span class="k-line__who">Aren</span><span class="k-time" tabindex="0" data-tip="19:08 · Day 1 · the night of the storm">7:08 pm</span></div><p class="k-line__body">Tobin, would you fetch us a round from the bar?</p><div class="k-reacts">{RE("feeling","tobin","heart","Tobin didn’t like that")}</div>
<div class="k-line__tools"><button aria-label="Previous take">{ic("left")}</button><span class="k-line__stamp">1/1</span><button aria-label="New take">{ic("right")}</button><button>{ic("edit")}Edit</button><button>{ic("eyeoff")}Hide</button></div></article>
<div class="k-note">{av("tobin",s=22,extra="filter:grayscale(.9)")}Tobin went to the bar.</div>
<article class="k-line" style="--speaker: var(--k-speaker-aren)"><div class="k-line__head"><span class="k-line__who">Aren</span><span class="k-time">7:12 pm</span></div><p class="k-line__body">Quickly, while he’s gone. I hid the guild ledger under the third floorboard behind the bar.</p><div class="k-reacts">{RE("memory","mira","spark","Mira will remember this")}{RE("warm","mira","heart","Mira trusts you a little more")}</div></article>
<article class="k-line" style="--speaker: var(--k-speaker-mira)"><div class="k-line__head"><span class="k-line__who">Mira</span><span class="k-time">7:14 pm</span></div><p class="k-line__body"><em>her eyes flick to the bar and back</em> Then stop saying it so loud.</p><div class="k-reacts">{RE("mood","mira","thought","Mira is worried for you")}</div></article></div>""",
 'Hover a time for 24-hour and the full story date. Hover a line for takes, Edit, Hide. Reactions are mostly feelings; “will remember” is saved for moments that matter.')
 + demo('Reaction kinds', '<div class="row">'+RE("feeling","tobin","heart","Tobin is suspicious of you")+RE("warm","mira","heart","Mira is glad to see you")+RE("mood","mira","thought","Mira is worried for you")+RE("belief","mira","help","Mira has her doubts")+RE("memory","mira","spark","Mira will remember this")+'</div>')
 + demo('Recall box', f'<div style="width:520px"><div class="k-recall"><b class="k-eyebrow" style="color:var(--k-scene-amber)">{ic("spark")} Mira remembered, vaguely</b><span style="font-family:var(--k-font-story);font-size:16px">The ledger is somewhere behind the bar.</span><small style="color:var(--k-scene-muted)">Six years ago she knew exactly where.</small></div></div>','The one place memory speaks up in the chat, when it changes the scene.')
 + demo('Edit a line', f"""<div style="width:620px"><div class="k-edit"><span style="font-family:var(--k-font-story);font-size:18px">Tobin, would you fetch us a round from the bar? And take your time.</span><div class="k-edit__warn">{ic("alert")}<span><b style="color:var(--k-scene-amber)">Regenerating from here rewrites the 5 messages after this one.</b> They’ll be kept as the previous take.</span></div><div style="display:flex;justify-content:flex-end;gap:8px"><button class="k-sbtn" style="border:0">Cancel</button><button class="k-sbtn">Save edit</button><button class="k-send">{ic("refresh")}Save and regenerate from here</button></div></div></div>""",'Save edit only changes what the model reads next. The warning appears when more than 2 messages follow.')
 + demo('Composer · Simple and Advanced', f"""<div style="display:flex;flex-direction:column;gap:18px;width:760px">
<div class="k-composer" style="position:relative;left:auto;right:auto;bottom:auto"><div class="k-composer__body"><label><span class="k-sr">Your line</span><textarea rows="2" placeholder="Speak or act as Aren…" style="width:100%">*leans closer* Then we meet at the lighthouse. Midnight.</textarea></label>
<div style="display:flex;justify-content:space-between;align-items:center"><span style="display:flex;gap:8px;align-items:center"><span class="k-detail-toggle"><button aria-pressed="true">Simple</button><button aria-pressed="false">Advanced</button></span><button class="k-sbtn" aria-label="Continue" style="width:32px;padding:0;justify-content:center;border-radius:50%">{ic("ff")}</button></span><span style="display:flex;gap:8px"><button class="k-mode" aria-haspopup="menu" aria-expanded="false">{ic("spark")}Auto <span class="k-mode__detected">· Do + Say</span>{ic("down")}</button><button class="k-send">Send{ic("send")}</button></span></div></div></div>
<div class="k-composer is-advanced" style="position:relative;left:auto;right:auto;bottom:auto;--used:.45"><div class="k-composer__meter"><i></i></div><div class="k-composer__body"><div class="k-composer__advanced" style="justify-content:space-between;align-items:center;padding-bottom:10px;border-bottom:1px solid rgba(255,236,210,.08);font-size:12.5px"><span style="display:flex;gap:8px;align-items:center">{av("mira",s=24)}<b>Only Mira will hear this</b><span style="color:var(--k-scene-muted)">Tobin is away</span></span><span style="display:flex;gap:6px"><button class="k-sbtn" aria-pressed="true">{ic("users")}Whoever fits</button><button class="k-sbtn">{av("mira",s=20)}Mira</button><button class="k-sbtn">{ic("quill")}Narrator</button></span></div>
<label><span class="k-sr">Your line</span><textarea rows="2" placeholder="Speak or act as Aren…" style="width:100%"></textarea></label>
<div style="display:flex;justify-content:space-between;align-items:center"><span style="display:flex;gap:8px;align-items:center"><span class="k-detail-toggle"><button aria-pressed="false">Simple</button><button aria-pressed="true">Advanced</button></span><button class="k-sbtn">{ic("clock")}Pass time</button><small style="color:var(--k-scene-muted)">~7,300 / 16,384 tokens</small></span><span style="display:flex;gap:8px"><button class="k-mode">{ic("spark")}Auto{ic("down")}</button><button class="k-stop">{ic("stop")}Stop</button></span></div></div></div></div>""",
 'Auto reads formatting: *action*, “speech”, (thought), @Mira whisper, &gt;&gt; narration. Picking a mode overrides it for one line.')
 + demo('Mode menu', '<div class="k-menu" role="menu" style="width:400px">'+''.join(f'<button role="menuitemradio" aria-checked="{"true" if i==0 else "false"}">{ic(n)}<span><b style="font-size:13.5px">{l}</b><br><small style="color:var(--k-scene-muted)">{d}</small></span><code>{c}</code></button>' for i,(l,n,d,c) in enumerate([('Auto','spark','Reads your formatting','*action* “speech” (thought)'),('Say','quote','Speak out loud','plain text'),('Do','hand','An action','*like this*'),('Whisper','ear','Only one person hears','@Mira like this'),('Think','thought','No one hears','(like this)'),('Narrate','quill','Direct the story','&gt;&gt; like this')]))+'</div>')
 + demo('Widgets', f'<div style="display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap"><div style="display:flex;flex-direction:column;gap:14px">{wchar}{wrow}</div><div style="display:flex;flex-direction:column;gap:14px">{wclock}{wmusic}</div></div>','Character (one each, any number), Story clock, Music, Place, Cast, Notes. Pinned widgets always show; unpinned ones appear when something happens to them.')
 + demo('Tiers (Backstage and Advanced only)', '<div class="row"><span class="k-tier">sharp</span><span class="k-tier k-tier--hazy">hazy</span><span class="k-tier k-tier--forgotten">forgotten</span></div>')
,'scene')

bs = section('backstage','Backstage lens · components','The same scene from behind: everything the engine knows. Mono type, blueprint lines.',
 demo('Panel + memory row', f'''<div class="k-bs-panel" style="width:820px"><div class="k-bs-title">MEMORY<button class="k-bs-btn">{ic("plus")}write a memory</button></div>
<div class="k-bs-row"><span class="k-bs-tier k-bs-tier--hazy">hazy</span><span>Aren hid the guild ledger somewhere behind the bar.<br><small class="k-mono" style="color:var(--k-bs-muted)">Day 1, 19:12 · faded Year 7</small></span><span class="k-mono" style="font-size:11.5px">witnessed<br>recall 0.82</span><span class="k-importance">{"".join('<i class="on"></i>' for _ in range(9))}<i></i></span><span><button class="k-bs-btn" aria-label="Pin">{ic("pushpin")}</button></span></div>
<div class="k-bs-row"><span class="k-bs-tier k-bs-tier--forgotten">forgotten</span><span style="opacity:.55">Tobin wore a green apron.</span><span class="k-mono" style="font-size:11.5px">witnessed</span><span class="k-importance"><i class="on"></i><i class="on"></i>{"".join("<i></i>" for _ in range(8))}</span><span></span></div></div>''')
 + demo('Mind node', '<div style="position:relative;height:90px;width:420px"><div class="k-mind-node is-win" style="left:0;top:0;width:190px;--a:.61"><span class="k-mono" style="font-size:10px;display:flex;justify-content:space-between;color:var(--k-bs-win)"><span>BELIEF</span><span>0.61</span></span><span style="font-size:12px">Ledger location: contested</span><span class="k-mind-node__bar"><i></i></span></div><div class="k-mind-node" style="left:220px;top:0;width:190px;--a:.34"><span class="k-mono" style="font-size:10px;display:flex;justify-content:space-between;color:var(--k-bs-line)"><span>PLACE</span><span>0.34</span></span><span style="font-size:12px">The Gull · night · rain</span><span class="k-mind-node__bar"><i></i></span></div></div>','Gold marks the path that won this turn.') + demo('Token bar', '<div style="width:520px"><div class="k-tokenbar">'+''.join(f'<i style="width:{v/16384*100:.1f}%;background:var(--k-bs-part-{n})"></i>' for n,v in [('rules',600),('cards',1450),('memory',820),('examples',540),('history',3600),('tail',290)])+'</div><p class="k-mono" style="font-size:12px">~7,300 / 16,384 tokens · 3 memories recalled · cache reuse 81%</p></div>')
 + demo('Buttons', f'<div class="row"><button class="k-bs-btn k-bs-btn--primary">{ic("refresh")}Read what is waiting now</button><button class="k-bs-btn">{ic("search")}Read again carefully</button></div>')
,'backstage')

html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kataki RPAI · Design system</title>
<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chewy&amp;family=Figtree:wght@400;500;600;700;800&amp;family=JetBrains+Mono:wght@400;500&amp;family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;1,6..72,400;1,6..72,500&amp;display=swap">
<link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="components.css">
<style>
body{{margin:0;font-family:var(--k-font-ui);color:var(--k-sky-ink);background:#f3f6fc}}
.top{{padding:48px 64px 24px;background:var(--k-sky-bg)}} .top h1{{font-family:var(--k-font-display);font-weight:400;font-size:64px;margin:0}} .top p{{max-width:760px;font-size:16px;line-height:1.5}}
nav.toc{{display:flex;gap:10px;padding:0 64px 24px;background:var(--k-sky-bg)}}
.sec{{padding:40px 64px}} .sec header h2{{margin:0;font-size:28px;font-weight:800}} .sec header p{{max-width:760px;line-height:1.5;opacity:.85}}
.sec h3{{margin:28px 0 12px;font-size:15px;text-transform:uppercase;letter-spacing:.1em}}
.sec--sky{{background:var(--k-sky-bg)}} .sec--scene{{background:#15100d;color:var(--k-scene-ink)}} .sec--backstage{{background:var(--k-bs-bg);background-image:var(--k-bs-grid);color:var(--k-bs-ink)}}
.sec--scene .demo__meta p,.sec--backstage .demo__meta p{{opacity:.75}}
.demo{{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:28px;padding:24px 0;border-top:1px solid rgba(127,127,127,.2)}}
.demo__meta p{{font-size:13px;line-height:1.5;margin:6px 0 0}}
.row{{display:flex;flex-wrap:wrap;gap:12px;align-items:center}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}}
.grid.dark{{background:#15100d;color:#f4e9da;padding:14px;border-radius:14px}} .grid.bp{{background:#06203f;color:#e4f0ff;padding:14px;border-radius:14px}}
.sw{{display:flex;align-items:center;gap:10px;font-size:13px}} .sw .chip{{width:36px;height:36px;border-radius:10px;border:1px solid rgba(127,127,127,.3);flex-shrink:0}} .sw code{{font-size:11px;opacity:.7;margin-left:auto}}
.types{{display:flex;flex-direction:column;gap:14px}} .type{{display:flex;justify-content:space-between;align-items:baseline;gap:20px;border-bottom:1px solid rgba(20,38,77,.08);padding-bottom:10px}} .type code{{font-size:11px;opacity:.7;white-space:nowrap}}
.icons{{display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:8px}} .ico{{display:flex;flex-direction:column;align-items:center;gap:6px;padding:12px 4px;border-radius:12px;background:rgba(255,255,255,.6)}} .ico .k-icon{{width:24px;height:24px}} .ico code{{font-size:10.5px}}
.hint{{font-size:13px}}
.k-tokenbar i{{display:block;height:12px}}
</style></head><body>
{sprite}
<div class="top"><h1>Kataki RPAI</h1><p>Design system for a local-first desktop app for AI role-play with characters who remember. Two worlds: <b>the Sky</b> (outside a story) and <b>the Scene</b> (inside one), plus the <b>Backstage lens</b>. Every class here lives in <code>components.css</code>; every value in <code>tokens.css</code>.</p></div>
<nav class="toc"><a class="k-chip" href="#foundations">Foundations</a><a class="k-chip" href="#sky">Sky</a><a class="k-chip" href="#scene">Scene</a><a class="k-chip" href="#backstage">Backstage</a><a class="k-chip" href="../screens/index.html">All screens</a></nav>
<main class="k-sky" style="background:none">{found}</main>
<div class="k-sky">{sky}</div>
<div class="k-scene">{scene}</div>
<div class="k-backstage">{bs}</div>
</body></html>'''
open(f'{O}/components.html','w').write(html)
print('ok')
